// File Variables

@protocol = http
@hostname = localhost
@port = 8090
@host = {{hostname}}:{{port}}
@baseUrl = {{protocol}}://{{host}}
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

@jwt = {{$dotenv AUTH_DATA_TOKEN}}
@accessToken = {{$dotenv GOOGLE_OAUTH_ACCESS_TOKEN}}
@refreshToken = {{$dotenv GOOGLE_OAUTH_REFRESH_TOKEN}}
@clientId = {{$dotenv CLIENT_ID}}
@clientSecret = {{$dotenv CLIENT_SECRET}}

// Requests

// アクセストークンが有効かどうか
# @name isAccessToken
GET https://oauth2.googleapis.com/tokeninfo?access_token={{$dotenv GOOGLE_OAUTH_ACCESS_TOKEN}} HTTP/1.1

###

// アクセストークンをリフレッシュする
# @name refeshAccessToken
POST https://oauth2.googleapis.com/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&refresh_token={{refreshToken}}
&client_id={{clientId}}
&client_secret={{clientSecret}}

###

// 認証済みユーザーのアクセストークンを取得
# @name getTokenAuthedUser
GET {{baseUrl}}/google/access_token HTTP/1.1
Authorization: {{jwt}}

###

@accessToken = {{getTokenAuthedUser.response.body.$.googleAccessToken}}
